### PR TITLE
[ci] fix ci by pinning dependencies to get node@6 to pass.

### PR DESCRIPTION
**Pull request by gabrielcsapo**
# Motivation

Getting #36 merged as a patch update.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@pzuraq I tried for about 3 hours to figure out why the deps for node-7 tests weren't working. They work with the lock file in the repo but for some reason they aren't working with ember-try.

**Comment by gabrielcsapo** [comment]
This change always runs the node-7 tests before every matrix.

**Comment by gabrielcsapo** [comment]
Passing CI for node@6 and once we patch the duplicate addons we can bump everything to latest.

**Comment by pzuraq** [comment]
I also think this is fine since we're just pinning devDeps for tests, we aren't making any other meaningful changes to the code. Merged to unblock the other PR, @gabrielcsapo like I said before I think either path forward here is ok, happy to merge a bugfix and release as a patch, but also equally happy to remove support for Babel 6 and Node < current LTS, and release a new major. I do think that the later solution would be better and would prefer it, but I don't have the time at the moment to take it on.

**Pull request merged**
