### PR TITLE
More parallel build related fixes

### PR DESCRIPTION
**Pull request by stefanpenner**
another one

### CODE REVIEW

**Comment by pzuraq** [comment]
Ah nevermind, I see it now. It resolves the path but not the actual plugin itself. Looks good!

**Comment by pzuraq** [comment]
I can’t release at the moment, but should be able to do it later tonight. Feel free to release in the meantime.

**Comment by stefanpenner** [comment]
The difference is, prior to this change we were providing a function as an argument to broccoli-babel-transpiler. Now we are providing a fully qualified path. A function is not serializable, but a string path is.

Broccoli-persistent-filter is smart enough to know, if it encounters a path in this position, it will simply require it, and utilize that require'd modules default export as the class it will instantiate.

More details: https://github.com/babel/broccoli-babel-transpiler#parallel-transpilation

**Comment by stefanpenner** [comment]
@pzuraq let me know when you have realized, I am also unable to now.

**Comment by pzuraq** [comment]
Released in v1.0.2

**Pull request merged**
